### PR TITLE
initial commit msa loading

### PR DESCRIPTION
**Pull request by sj900**
PR implement msa loading functions
1. Implement load_msa_from_msa_dir in inputs.py
2. Creates msa_parsing.py and make_msa_features/mask that reuses AF2 msa loading functions
3. Added a test script that loads an msa and creates a batched_atom_input

### CODE REVIEW

**Comment by amorehead** [comment]
Thanks @sj900 for your hard work on this new MSA pipeline! I'll fix the tests locally and push the changes remotely soon. Also, I'll merge this into Phil's `main` branch shortly thereafter.

Do you have an idea what it would take to adapt this MSA logic for RNA and DNA chains as well? And perhaps we can keep a similar format for the template loading pipeline?

**Comment by sj900** [comment]
@amorehead No problem! Sounds good.

I'm not sure what it will take to adapt the MSA logic to DNA and RNA but I will look into it and let you know. I'll make sure to keep a similar format for the template loading pipeline.

**Comment by amorehead** [comment]
@sj900, thanks! By the way, @milot-mirdita just shared with me (and I've uploaded to this fork) some test MSAs and templates to use with a handful of example PDB mmCIF files (7a4d, 209d, and 721p): `https://github.com/amorehead/alphafold3-pytorch-lightning-hydra/tree/main/data/test`

**Comment by amorehead** [comment]
@sj900, just a heads up, I decided to implement most of the generic MSA parsing and loading to handle protein, RNA, DNA, and ligand chains ([latest commit](https://github.com/amorehead/alphafold3-pytorch-lightning-hydra/commit/1556b1aa2c7440112c70e8abd665c7d45459ffff)). The only thing left to do is add a new DNA/RNA-equivalent pattern to Uniprot's pattern that you added for protein chain species parsing (to support MSA chain parsing for interfaces). I'd recommend focusing on template parsing for now, since we can revisit MSA chain pairing later on (unless you want to add this now)

**Comment by sj900** [comment]
@amorehead Thanks for letting me know. Ill focus on template parsing for now and revisit MSA chain pairing later on.

**Pull request merged**
